API_KEY: 'AIzaSyCemp9l0cUOsPSOAnmCfp5aekNqIg41WP0'

CLOUD_API_KEY: '664259755638162'
CLOUD_SECRET: 'A6BiPixJqJ7hT-uhZtIpRG0w17o'

S3_KEY: 'AKIAIXVHC5KLS2NZ4DBA'
S3_SECRET: '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'
S3_BUCKET_NAME: 'donut-stephanie-pickles4343434349999922'
S3_REGION: 'us-east-1'
