API_KEY: 'AIzaSyCemp9l0cUOsPSOAnmCfp5aekNqIg41WP0'

CLOUD_API_KEY: '664259755638162'
CLOUD_SECRET: 'A6BiPixJqJ7hT-uhZtIpRG0w17o'

S3_BUCKET: 'charlielikesdonuts'
AWS_ACCESS_KEY_ID: 'AKIAJTN7XTYSOOPPJFUA'
AWS_SECRET_ACCESS_KEY: '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'