# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58308ef76fa913ff0f85736059c24a258717d076d07056691c014e7d23394084b9e649603990debda5493001c09d375c1ed8ee9dd3a570069a5416c4105b2feb

test:
  secret_key_base: 79b18561df82ba0f5922c31cb32c07c7592231ea80a63cdd48e485650b292a37870f0a5a25a4c64c4d8d1fbf92705a613d056c057d75c8713046094a530dc1b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
